version: "3.9"

services:
  app:
    image: 332696939752.dkr.ecr.us-east-1.amazonaws.com/faceid-api:latest
    ports:
      - '8000:8000'
    volumes:
      - ./app/:/app
      - ./dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=kalman
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=kalman
    ports:
      - '54032:5432'

volumes:
  dev-db-data:
  dev-static-data:

