---
name: gcs-deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-push-gcr:
    name: deploy-gcr
    runs-on: Ubuntu-20.04
    env:
      IMAGE_NAME: fast-face
      PROJECT_ID: django-microservices-347306
    steps:
      - name: Checkout
        uses: actions/chekcout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
          project_id: ${{ env.PROJECT_ID }}
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet

      - name: Push Docker Image to Container Registery (GCR)
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
