---
name: aws-deploy
on: [ push ]

jobs:
  deploy:
    name: deploy
    runs-on: Ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: kenanbolat/faceid-api
      - name : list contents
        run : ls -ltr
      - name : docker context
        run : docker context create ecs myecs
      - name : docker context use myecs
        run : docker context use myecs
      - name : docker compose up
        run : docker compose up



